export const iconSet = {
    SHOWER: "fa fa-shower",
    SNOWFLAKE: "fa fa-snowflake-o",
    CAMPFIRE: "fa fa-free-code-camp",
    BELL: "fa fa-bell-o",
    BINOCULARS: "fa fa-binoculars",
    BICYCLE: "fa fa-bicycle",
    BOOK: "fa fa-book",
    BRIEFCASE: "fa fa-briefcase",
    BUS: "fa fa-bus",
    COFFE: "fa fa-coffee",
    CUBES: "fa fa-cubes",
    AIRPLANE: "fa fa-fighter-jet",
    EYE: "fa fa-eye",
    FLAG: "fa fa-flag",
    FLASK: "fa fa-flask",
    // GIFT: "fa fa-gift",
    // GLOBE: "fa fa-globe",
    // HEADPHONES: "fa fa-headphones",
    // BED: "fa fa-bed",
    // HEART: "fa fa-heart-o",
    // WAND: "fa fa-magic",
    // FOOTBALL: "fa fa-futbol-o",
    // TREE: "fa fa-tree",
    // TV: "fa fa-television",
    // UMBRELLA: "fa fa-umbrella",
    // UNIVERSITY: "fa fa-university",
    // CAMERA: "fa fa-video-camera",
    // WHEELCHAIR: "fa fa-wheelchair",
    // WRENCH: "fa fa-wrench"
};
export const defaultIcon = "fa fa-bars";